import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import WebSocket from 'ws';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';
import { VERSION } from '../version.js';
import { openBrowser } from '../utils/open-browser.js';

interface AgentConfig {
    relayUrl?: string;
    deviceId?: string;
    token?: string;
}

interface AgentOptions {
    relayUrl?: string;
    deviceId?: string;
    token?: string;
    persistSession?: boolean;
    debug?: boolean;
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DEFAULT_MCP_ENTRY = path.resolve(__dirname, '../index.js');
const CONFIG_DIR = path.join(os.homedir(), '.system-commander-device');
const CONFIG_PATH = path.join(CONFIG_DIR, 'device.json');
const DEFAULT_RELAY_URL = process.env.SYSTEM_COMMANDER_RELAY_URL || '';
const DASHBOARD_PORT = Number(process.env.SYSTEM_COMMANDER_DASHBOARD_PORT) || 4319;

function logDebug(enabled: boolean, ...args: any[]) {
    if (enabled) console.debug('[system-commander]', ...args);
}

const RESET = '\x1b[0m';
const ACCENT = '\x1b[38;5;75m';
const MUTED = '\x1b[38;5;245m';
const WHITE = '\x1b[97m';
const GREEN = '\x1b[92m';
const RED = '\x1b[91m';

export type RemoteFailureCode =
    | 'CONFIGURATION'
    | 'LOCAL_ENGINE'
    | 'TOKEN_INVALID'
    | 'TOKEN_EXPIRED'
    | 'DEVICE_NOT_REGISTERED'
    | 'CLOUD_UNREACHABLE'
    | 'CLOUD_PROTOCOL'
    | 'CLOUD_AUTH'
    | 'RATE_LIMITED'
    | 'INVALID_REGISTRATION'
    | 'REGISTRATION_TIMEOUT'
    | 'AUTH_SERVICE_UNAVAILABLE'
    | 'CLOUD_CONNECTION';

export class RemoteAgentError extends Error {
    readonly code: RemoteFailureCode;
    readonly retryable: boolean;
    readonly action: string;

    constructor(message: string, code: RemoteFailureCode, action: string, retryable = false) {
        super(message);
        this.name = 'RemoteAgentError';
        this.code = code;
        this.retryable = retryable;
        this.action = action;
    }
}

function asRemoteAgentError(
    error: any,
    fallbackCode: RemoteFailureCode,
    fallbackMessage: string,
    fallbackAction: string,
    retryable = false,
): RemoteAgentError {
    if (error instanceof RemoteAgentError) return error;

    const message = error?.message || String(error);
    if (/ENOTFOUND|EAI_AGAIN|ECONNREFUSED|ETIMEDOUT|ECONNRESET|network|socket hang up/i.test(message)) {
        return new RemoteAgentError(
            'System Commander could not reach the Cloud relay.',
            'CLOUD_UNREACHABLE',
            'Check the relay URL and your internet connection, then run the command again.',
            true,
        );
    }

    return new RemoteAgentError(message || fallbackMessage, fallbackCode, fallbackAction, retryable);
}

function authFailureFromMessage(message: string, code?: string): RemoteAgentError {
    const normalizedCode = String(code || '').toUpperCase();
    const normalized = message.toLowerCase();

    if (normalizedCode === 'RATE_LIMITED') {
        return new RemoteAgentError(
            'The Cloud relay is temporarily rate-limiting this device.',
            'RATE_LIMITED',
            'Wait a moment before retrying. If this keeps happening, check that you are not running multiple System Commander agents for the same device.',
            true,
        );
    }

    if (normalizedCode === 'INVALID_REGISTRATION' || normalizedCode === 'REGISTRATION_TIMEOUT') {
        return new RemoteAgentError(
            message,
            normalizedCode === 'REGISTRATION_TIMEOUT' ? 'REGISTRATION_TIMEOUT' : 'INVALID_REGISTRATION',
            'Copy and run the complete device command generated by System Commander Cloud. Do not modify the device ID or token.',
        );
    }

    if (normalizedCode === 'AUTH_SERVICE_UNAVAILABLE') {
        return new RemoteAgentError(
            'System Commander Cloud could not verify the device right now.',
            'AUTH_SERVICE_UNAVAILABLE',
            'Check your internet connection and try again. If the problem persists, verify the Cloud relay is online.',
            true,
        );
    }

    if (normalizedCode === 'TOKEN_EXPIRED' || normalized.includes('token expired')) {
        return new RemoteAgentError(
            'Your System Commander device token has expired.',
            'TOKEN_EXPIRED',
            'Sign in to System Commander Cloud, rotate this device token, and run the new command exactly as provided.',
        );
    }

    if (normalizedCode === 'DEVICE_NOT_REGISTERED' || normalized.includes('device is not registered') || normalized.includes('device not found')) {
        return new RemoteAgentError(
            'This System Commander device is no longer registered in the Cloud account.',
            'DEVICE_NOT_REGISTERED',
            'Open System Commander Cloud, create a fresh device registration, and run the new command.',
        );
    }

    if (normalizedCode === 'TOKEN_INVALID' || normalized.includes('invalid system commander device token') || normalized.includes('invalid device token')) {
        return new RemoteAgentError(
            'The device token was rejected by System Commander Cloud.',
            'TOKEN_INVALID',
            'Copy the complete device command from System Commander Cloud and run it again. Do not reuse an older token.',
        );
    }

    return new RemoteAgentError(
        message || 'System Commander Cloud rejected this device authentication request.',
        'CLOUD_AUTH',
        'Check that the device ID and token came from the same current System Commander Cloud registration.',
    );
}

function clearLine() {
    if (process.stdout.isTTY) process.stdout.write('\r\x1b[2K');
}

function printStep(icon: string, message: string, color = WHITE) {
    console.log('  ' + icon + '  ' + color + message + RESET);
}

function runSpinner(message: string) {
    if (!process.stdout.isTTY) {
        printStep('·', message, MUTED);
        return { stop: (_success = true, _finalMessage = message) => undefined };
    }

    const frames = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏'];
    let index = 0;
    process.stdout.write('  ' + ACCENT + frames[index] + RESET + '  ' + MUTED + message + RESET);
    const timer = setInterval(() => {
        index = (index + 1) % frames.length;
        clearLine();
        process.stdout.write('  ' + ACCENT + frames[index] + RESET + '  ' + MUTED + message + RESET);
    }, 90);

    return {
        stop(success = true, finalMessage = message) {
            clearInterval(timer);
            clearLine();
            printStep(success ? '✓' : '✕', finalMessage, success ? GREEN : RED);
        },
    };
}

export class SystemCommanderRemoteAgent {
    private relayUrl: string;
    private deviceId: string;
    private token: string | null;
    private persistSession: boolean;
    private debug: boolean;
    private ws: WebSocket | null = null;
    private client: Client | null = null;
    private transport: StdioClientTransport | null = null;
    private reconnectTimer: NodeJS.Timeout | null = null;
    private shuttingDown = false;
    private reconnecting = false;

    constructor(options: AgentOptions = {}) {
        this.relayUrl = options.relayUrl || DEFAULT_RELAY_URL;
        this.deviceId = options.deviceId || process.env.SYSTEM_COMMANDER_DEVICE_ID || os.hostname();
        this.token = options.token || process.env.SYSTEM_COMMANDER_DEVICE_TOKEN || null;
        this.persistSession = options.persistSession !== false;
        this.debug = options.debug === true;
    }

    async run(): Promise<void> {        await this.loadConfig();

        if (!this.relayUrl) {
            throw new RemoteAgentError(
                'No System Commander Cloud relay URL is configured.',
                'CONFIGURATION',
                'Run the device command generated by System Commander Cloud, or provide --relay <https://your-relay>.',
            );
        }
        if (!this.token) {
            throw new RemoteAgentError(
                'No System Commander device token is configured.',
                'CONFIGURATION',
                'Run the device command generated by System Commander Cloud, or provide --token <token>.',
            );
        }

        await this.startLocalMcp();
        this.installSignals();
        await this.connectLoop();
    }

    async logout(): Promise<void> {
        await fs.rm(CONFIG_PATH, { force: true });
        console.log('🔓 System Commander device credentials removed.');
        console.log('   ' + CONFIG_PATH);
    }

    private async loadConfig(): Promise<void> {
        try {
            const raw = await fs.readFile(CONFIG_PATH, 'utf8');
            const saved = JSON.parse(raw) as AgentConfig;
            if (!this.relayUrl && saved.relayUrl) this.relayUrl = saved.relayUrl;
            if (!process.env.SYSTEM_COMMANDER_DEVICE_ID && saved.deviceId) this.deviceId = saved.deviceId;
            if (!this.token && saved.token) this.token = saved.token;

            logDebug(this.debug, 'Loaded persisted device configuration.');
        } catch (error: any) {
            if (error?.code !== 'ENOENT') {
                logDebug(this.debug, 'No usable saved config:', error?.message);
            }
        }
    }

    private async saveConfig(): Promise<void> {
        if (!this.persistSession || !this.token) return;
        await fs.mkdir(CONFIG_DIR, { recursive: true });

        const tmpPath = CONFIG_PATH + '.' + process.pid + '.tmp';
        await fs.writeFile(
            tmpPath,
            JSON.stringify(
                {
                    relayUrl: this.relayUrl,
                    deviceId: this.deviceId,
                    token: this.token,
                },
                null,
                2            ),
            { mode: 0o600 }
        );
        await fs.rename(tmpPath, CONFIG_PATH);
    }

    private async startLocalMcp(): Promise<void> {
        const mcpEntry = process.env.SYSTEM_COMMANDER_MCP_ENTRY || DEFAULT_MCP_ENTRY;

        this.transport = new StdioClientTransport({
            command: process.execPath,
            args: [mcpEntry],
            env: {
                ...process.env,
                DC_REMOTE_DEVICE: 'true',
                SYSTEM_COMMANDER_REMOTE_AGENT: 'true',
            },
        });

        this.client = new Client(
            {
                name: 'system-commander-remote-agent',
                version: VERSION,
            },
            { capabilities: {} }
        );

        const spinner = runSpinner('Starting local engine…');
        try {
            await this.client.connect(this.transport);
            spinner.stop(true, 'Local engine ready');
        } catch (error: any) {
            spinner.stop(false, 'Local engine failed to start');
            throw asRemoteAgentError(
                error,
                'LOCAL_ENGINE',
                'System Commander could not start its local engine.',
                'Make sure the System Commander installation is complete and rebuild it with npm run build, then try again.',
            );
        }

        const tools = await this.client.listTools();
        logDebug(this.debug, 'Local MCP ready with ' + (tools.tools?.length ?? 0) + ' tools.');
        await this.saveConfig();
    }

    private async connectLoop(): Promise<void> {
        if (this.reconnecting || this.shuttingDown) return;
        this.reconnecting = true;

        try {
            while (!this.shuttingDown) {
                try {
                    await this.connectOnce();
                    return;
                } catch (error: any) {
                    if (this.shuttingDown) return;

                    const failure = asRemoteAgentError(
                        error,
                        'CLOUD_CONNECTION',
                        'System Commander Cloud connection failed.',
                        'Check the relay URL and try again.',
                    );

                    printStep('!', failure.message, RED);
                    printStep('→', 'Next step: ' + failure.action, MUTED);

                    if (!failure.retryable) {
                        await this.shutdown();
                        return;
                    }
                    await this.waitForReconnect();
                }
            }
        } finally {
            this.reconnecting = false;
        }
    }

    private connectOnce(): Promise<void> {        return new Promise((resolve, reject) => {
            const websocketUrl = this.toWebSocketUrl(
                this.relayUrl.replace(/\/$/, '') + '/device/connect'
            );

            logDebug(this.debug, 'Connecting to', websocketUrl);
            const spinner = runSpinner('Connecting to System Commander Cloud…');

            const ws = new WebSocket(websocketUrl);
            this.ws = ws;
            let settled = false;
            let reconnectOnClose = true;

            const finishReject = (error: Error) => {
                if (settled) return;
                settled = true;
                reject(error);
            };

            ws.on('open', async () => {
                try {
                    const tools = await this.client!.listTools();

                    ws.send(
                        JSON.stringify({
                            type: 'register',
                            deviceId: this.deviceId,
                            token: this.token,
                            protocol: 1,                            capabilities: { tools: true },
                            tools: tools.tools || [],
                        })
                    );
                } catch (error: any) {
                    finishReject(error instanceof Error ? error : new Error(String(error)));
                    ws.close();
                }
            });

            ws.on('message', async (raw) => {
                let message: any;
                try {
                    message = JSON.parse(raw.toString());
                } catch {
                    return;
                }

                if (message.type === 'registered') {
                    spinner.stop(true, 'Connected to System Commander Cloud');
                    printStep('✓', 'Device registered  ' + this.deviceId, WHITE);
                    console.log();
                    printStep('✓', 'System Commander is ready for AI connections', GREEN);
                    await this.openDashboard();
                    if (!settled) {
                        settled = true;
                        resolve();
                    }                    return;
                }

                if (message.type === 'auth_error') {
                    spinner.stop(false, 'Device authentication failed');
                    reconnectOnClose = false;
                    finishReject(authFailureFromMessage(message.message || 'System Commander Cloud rejected this device.', message.code));
                    ws.close();
                    return;
                }

                if (message.type === 'list_tools') {
                    try {
                        const tools = await this.client!.listTools();
                        ws.send(JSON.stringify({
                            type: 'list_tools_result',
                            requestId: message.requestId,
                            result: tools,
                        }));
                    } catch (error: any) {
                        this.sendError(message.requestId, error);
                    }
                    return;
                }
                if (message.type === 'tool_call') {
                    try {
                        const result = await this.client!.callTool({
                            name: message.name,
                            arguments: message.arguments || {},
                        });

                        ws.send(JSON.stringify({
                            type: 'tool_result',
                            requestId: message.requestId,
                            result,
                        }));
                    } catch (error: any) {
                        this.sendError(message.requestId, error);
                    }
                }
            });

            ws.on('close', (code, reason) => {
                this.ws = null;
                const closeReason = reason?.toString() || '';
                if (!settled) {
                    spinner.stop(false, 'Connection to System Commander Cloud failed');
                    if (!reconnectOnClose) return;
                    finishReject(new RemoteAgentError(
                        closeReason || `The Cloud relay closed the connection before registration (code ${code}).`,
                        'CLOUD_CONNECTION',
                        'Check that the relay is online and the relay URL is correct, then try again.',
                        true,
                    ));
                } else if (!this.shuttingDown && reconnectOnClose) {
                    console.log(MUTED + '  Cloud connection closed. Reconnecting automatically…' + RESET);
                    void this.connectLoop();
                }
            });
            ws.on('error', (error) => {
                logDebug(this.debug, 'WebSocket error:', error.message);
                if (!settled) {
                    spinner.stop(false, 'Connection to System Commander Cloud failed');
                    finishReject(asRemoteAgentError(
                        error,
                        'CLOUD_CONNECTION',
                        'System Commander Cloud connection failed.',
                        'Check the relay URL and your internet connection, then try again.',
                        true,
                    ));
                }
            });
        });
    }

    private sendError(requestId: string, error: any) {
        if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;

        this.ws.send(JSON.stringify({
            type: 'tool_result',
            requestId,
            result: {
                content: [{
                    type: 'text',
                    text: error instanceof Error ? error.message : String(error),
                }],
                isError: true,
            },
        }));
    }

    private async openDashboard(): Promise<void> {
        const url = `http://localhost:${DASHBOARD_PORT}`;
        try {
            await openBrowser(url);
            printStep('↗', 'Live dashboard opened  ' + url, MUTED);
        } catch (error: any) {
            printStep('!', 'Could not open the live dashboard automatically', MUTED);
            logDebug(this.debug, 'Dashboard open failed:', error?.message || String(error));
        }
    }

    private async waitForReconnect(): Promise<void> {
        const delay = 2000 + Math.floor(Math.random() * 3000);
        await new Promise((resolve) => {
            this.reconnectTimer = setTimeout(resolve, delay);
        });    }

    private toWebSocketUrl(url: string): string {
        if (url.startsWith('https://')) return 'wss://' + url.slice('https://'.length);
        if (url.startsWith('http://')) return 'ws://' + url.slice('http://'.length);
        if (url.startsWith('ws://') || url.startsWith('wss://')) return url;
        return 'wss://' + url;
    }

    private installSignals() {
        const shutdown = () => {
            void this.shutdown();
        };

        process.once('SIGINT', shutdown);
        process.once('SIGTERM', shutdown);
    }

    async shutdown(): Promise<void> {
        if (this.shuttingDown) return;
        this.shuttingDown = true;

        if (this.reconnectTimer) clearTimeout(this.reconnectTimer);

        try {
            if (this.ws?.readyState === WebSocket.OPEN) {
                this.ws.close(1000, 'client shutdown');
            }        } catch {}

        try {
            await this.client?.close();
        } catch {}

        try {
            await this.transport?.close();
        } catch {}

        this.ws = null;
        console.log('\n🛑 System Commander remote agent stopped.');
    }
}
